# Stage 1: Build Stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production Stage
FROM node:20-alpine

WORKDIR /app
COPY --from=build /app ./

EXPOSE 3000
CMD ["npm", "start"]
