# Stage 1: Build Stage
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Stage 2: Production Stage
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy the built application and dependencies from the build stage
COPY --from=build /app /app

# Expose port 3000
EXPOSE 3000

# Run the app in production mode
CMD ["npm", "start"]
